#!/bin/bash

#*******************************************************************************
#*                                   XDebRepo                                  *
#*-----------------------------------------------------------------------------*
#*                                                                             *
#* Copyright (c) 2022 Ivan Danov                                               *
#*                                                                             *
#* MIT License                                                                 *
#*                                                                             *
#* Permission is hereby granted, free of charge, to any person obtaining a     *
#* copy of this software and associated documentation files (the "Software"),  *
#* to deal in the Software without restriction, including without limitation   *
#* the rights to use, copy, modify, merge, publish, distribute, sublicense,    *
#* and/or sell copies of the Software, and to permit persons to whom the       *
#* Software is furnished to do so, subject to the following conditions:        *
#*                                                                             *
#* The above copyright notice and this permission notice shall be included     *
#* in all copies or substantial portions of the Software.                      *
#*                                                                             *
#* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS     *
#* OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, *
#* FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE *
#* AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER      *
#* LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING     *
#* FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER         *
#* DEALINGS IN THE SOFTWARE.                                                   *
#*******************************************************************************

SCRIPT_PATH=$(realpath "$(dirname "$0")")
export SCRIPT_PATH
export XDEBREPO_CONF_DIR_BASE=${SCRIPT_PATH}

export REPO_PATH=/repo


if [ $# -ne 3 ]; then
	echo "ERROR: args: '$#': '$0' '$1' '$2' '$3' '$4' '$5'"
	exit 1
fi

cd "${SCRIPT_PATH}" || exit 1
echo "xdebrepo repo add '${1}' '${2}' '${REPO_PATH}/tmp/${1}/${3}'"
bash xdebrepo repo add "${1}" "${2}" "${REPO_PATH}/tmp/${1}/${3}"
res=$?
rm "${REPO_PATH}/tmp/${1}/${3}"

exit ${res}
