#!/bin/bash

export SCRIPT_PATH=$(realpath $(dirname $0))
export XDEBREPO_CONF_DIR_BASE=${SCRIPT_PATH}/testrepo

if [ $# -ne 3 ]; then
	echo "ERROR: args: '$#': '$0' '$1' '$2' '$3' '$4' '$5'"
	exit 1
fi

cd ${SCRIPT_PATH}
echo "xdebrepo repo add '${1}' '${2}' 'tmp/${1}/${3}'"
bash xdebrepo repo add "${1}" "${2}" "tmp/${1}/${3}"
res=$?
# rm tmp/${3}

exit ${res}
