name: Build debian package
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Create tag
      id: create_tag
      run: |
        tag=$(make info")
        echo "::set-output name=tag::$tag"
    
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.create_tag.outputs.tag }}
        release_name: ${{ steps.create_tag.outputs.tag }}
        draft: true
        prerelease: false

    - uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./xdebrepo_*_all.deb
        asset_name: xdebrepo_*_all.deb
        asset_content_type: application/vnd.debian.binary-package

    - uses: eregon/publish-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        release_id: ${{ steps.create_release.outputs.id }}


  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install jq tool
      run: |
        sudo apt-get update
        sudo apt-get install git git2cl lintian

    - name: Show info
      run: make info

    - name: Create deb package
      run: make deb

    - name: Display artifacts
      run: ls -R xdebrepo_*_all.deb
      working-directory: .

    - name: Save artifacts
      uses: actions/upload-artifact@v2
      with:
        name: xdebrepo
        path: xdebrepo_*_all.deb
