name: Makefile CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Install jq tool
      run: |
        sudo apt-get update
        sudo apt-get install git git2cl lintian

    - name: Show info
      run: make info
      
    - name: Create deb package
      run: make deb
      
    - name: Display artifacts
      run: ls -R xdebrepo_*_all.deb
      working-directory: .

    - name: Save artifacts
      uses: actions/upload-artifact@v2
      with:
        name: xdebrepo
        path: xdebrepo_*_all.deb
        
